<?xml version="1.0" encoding="utf-8"?>
<Database Name="LsoCoreTestOps" Class="OpsDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.0.5.14;Initial Catalog=LsoCoreTestOps;User ID=L5development" SettingsObjectName="SQL2kDBML.Properties.Settings" SettingsPropertyName="LsoCoreTestOpsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CustContactName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CustContactPhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PriceSchedule" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOpened" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LSOContactEmpNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SalesRepEmpNum" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RestartDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SICCode" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="HowHearAbout" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOWBillingCode" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="CreditLimit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreditAvail" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="AcctStatus" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NetDueDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InterestPercent" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="PayMethodID" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CardType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CardExpMonth" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CardExpYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameOnCard" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="HeldCycleCount" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EditDateTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LastEditEmp" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LastShipDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="BillToAttnName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BillToAddress1" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="BillToAddress2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="BillToCity" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BillToState" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="BillToZip" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="PhyAddress1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="PhyAddress2" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="PhyCity" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PhyState" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="PhyZip" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="WaivePUFee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LocCode" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="WaiveFuelFee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PageCount" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BillToID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDICustomer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastStatusEditDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LastStatusEditEmp" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="OnHoldOverride" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="First60DayRev" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Hit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LinkedCustID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WaiveResDelivFee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StarCustomer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WaiveDimWt" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="KnownShipper" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReferralRep" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="BillingRefRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentCustID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InheritDiscounts" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WaiveSignatureFee" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="WaiveRemoteDeliveryFee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WaiveManualProcessingFee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WaiveOnCallFee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DisallowSimplePricing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="newCustomerReferralSourceID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeclaredValueSignature" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TieredDiscountWindow" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WaiveSecuredFacilityFee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WaivePickupEventFee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Customer_NewCustomerOption" Member="NewCustomerOptions" ThisKey="CustID" OtherKey="CustID" Type="NewCustomerOption" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Package" Member="Packages">
    <Type Name="Package">
      <Column Name="AirbillNo" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PickUpLocID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DestinationLocID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillToCustID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CardType" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="ExpMonth" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ExpYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNumber" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="NameOnCard" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ServiceType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReleaseSignature" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AuthorizedReleaseName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LetterType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PkgWeight" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Pieces" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Length" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Width" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Height" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="WgtVolume" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DeclaredValue" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="BillingRef" Type="System.String" DbType="Char(70)" CanBeNull="true" />
      <Column Name="RegCharge" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="AddInsCharge" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ServiceCharge" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TotalCharge" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PickupHubCity" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="PickupDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="PickupTime" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="PickupBoxID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PickupRoute" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="PickupEmpNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PickupComments" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PickupInputDateTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="PickupInputEmpNum" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Transmitted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Carrier" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="DelivRouteStop" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DelivRoute" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="DelivStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ArriveHubCode" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="ArriveDateTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ArriveEmpNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DelivDateTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DelivSignatureName" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="DelivEmpNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DelivComments" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="DelivInputDateTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DelivInputEmpNum" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="SrvFailLateCode" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="OtherChargesOne" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OtherChargesTwo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ToAttnName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FromAttnName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ToCoName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ToAddress1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ToAddress2" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ToCity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ToState" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ToZip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ToPhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FromcoName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FromAddress1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="FromAddress2" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="FromCity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FromState" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="FromZip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FromPhone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="User1" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="User2" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="User3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="User4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="User5" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="User6" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="User7" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="User8" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ResidentialDelivery" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Zone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PickupFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ResDelivFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LSOPackingUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BillingRef2" Type="System.String" DbType="Char(70)" CanBeNull="true" />
      <Column Name="BillingRef3" Type="System.String" DbType="Char(70)" CanBeNull="true" />
      <Column Name="BillingRef4" Type="System.String" DbType="Char(70)" CanBeNull="true" />
      <Column Name="SystemGenerated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PromoCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SignatureRequirement" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SignatureFee" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="RemoteDeliveryFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ManualProcessingFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OnCallFeeAssessed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DispatchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecurityFee" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="UseSimplePricing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HippaDelivery" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HippaDeliveryFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SecuredFacilityFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="UndiscountedRegCharge" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DiscountedFSC" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="UndiscountedFSC" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewCustomerOption" Member="NewCustomerOptions">
    <Type Name="NewCustomerOption">
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CCOptOut" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Customer_NewCustomerOption" Member="Customer" ThisKey="CustID" OtherKey="CustID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_GetCustID" Method="sp_GetCustID">
    <Parameter Name="CUSTID" Parameter="cUSTID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spRestoreAllTestState" Method="spRestoreAllTestState">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spRestoreLsoCustomerRepositoryTestState" Method="spRestoreLsoCustomerRepositoryTestState">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_GetCustomerBaseDiscounts" Method="sp_GetCustomerBaseDiscounts">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetCustomerBaseDiscountsResult">
      <Column Name="serviceid" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPercent" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetCustomerTierRevenueDiscounts" Method="sp_GetCustomerTierRevenueDiscounts">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetCustomerTierRevenueDiscountsResult">
      <Column Name="Serviceid" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="RevenueCeiling" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPercent" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="tiereddiscountwindow" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetCustomerWeightDiscounts" Method="sp_GetCustomerWeightDiscounts">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetCustomerWeightDiscountsResult">
      <Column Name="serviceid" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="startweight" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="endweight" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPercent" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetCustomerZoneDiscounts" Method="sp_GetCustomerZoneDiscounts">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetCustomerZoneDiscountsResult">
      <Column Name="serviceid" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="zone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPercent" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetTrackingData" Method="sp_GetTrackingData">
    <Parameter Name="Airbillno" Parameter="airbillno" Type="System.String" DbType="Char(8)" />
    <ElementType Name="sp_GetTrackingDataResult">
      <Column Name="StatusCode" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="StatusDescription" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="EventTimeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="TrackingCode" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>